version: 2.1
orbs:
  node: circleci/node@4.3.0
  slack: circleci/slack@4.3.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    docker:
      - image: node:current
    working_directory: ~/circle-ci
    steps:
      - checkout
      #- node/install-packages:
      #    cache-path: ~/project/node_modules
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules  
      - run: yarn build
  #    - run: yarn test
  #    - slack/notify:
  #        channel: testintegracao
  #        event: pass
  #        template: basic_success_1
  #    - slack/notify:
  #        channel: testintegracao
  #        event: fail
  #        template: basic_fail_1
  deploy:
        executor: 
          aws-cli/default
        steps:
          - checkout
          - attach_workspace:
              at: .
          - aws-cli/setup
          - run:
              name: Upload file to S3
              command: aws s3 sync ~/build/ s3://circleci-test-react --acl public-read


workflows:
  build_and_notify:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: AWS_ACCESS_TOKEN