version: 2.1
orbs:
  node: circleci/node@4.3.0
  slack: circleci/slack@4.3.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
              install-yarn: true
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn install
          pkg-manager: yarn
  notify:
    executor:
      name: node/default
    steps:
      - node/install:
          install-yarn: true
      - run: yarn build
      - run: yarn test
      - slack/notify:
          channel: testintegracao
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: testintegracao
          event: fail
          template: basic_fail_1

workflows:
  build_and_notify:
    jobs:
      - build
      - notify:
          requires:
            - build
 


