version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  node: circleci/node@4.3.0
  slack: circleci/slack@4.3.0
jobs:
  build:
    docker:
      - image: cimg/node:default
    steps:
      - checkout
      - run: node --version
