version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.3.0
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - slack/notify:
          channel: testintegração
          event: pass
          template: basic_success_1

workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context:
            - slack-secrets

