version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.1
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          color: '#32788D'
          message: Tests passed
          title: Testing Slack Orb
          author_name: Marcão
          webhook: https://hooks.slack.com/services/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
workflows:
  node-tests:
    jobs:
      - node/test
