version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  node: circleci/node@4.3.0
  slack: circleci/slack@4.3.0
jobs:
  build:
    docker:
      - image: cimg/node:13.10
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}        
            - v1-dependencies-
      - run:    
          name: Building    
          command: yarn build
      - run:    
          name: Testing    
          command: yarn test
      - slack/notify:
          channel: testintegracao
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: testintegracao
          event: fail
          template: basic_fail_1
workflows:
  build_and_notify:
    jobs:
      - build
